(define (problem n-puzzle)
  (:domain puzzle)
  (:objects
    p1 p2 p3 p4 p5 p6 p7 p8 p9 - position
    n1 n2 n3 n4 n5 n6 n7 n8 - numero
  )
  (:init
    (at  p1 n1) 
    (at  p2 n2) 
    (at  p3 n3)
    (at  p4 n4) 
    (at  p5 n5) 
    (at  p6 n6)
    (at  p7 n7) 
    (at  p8 n8) 
    (empty p9)
    (adjacent p1 p2) 
    (adjacent p2 p1) 
    (adjacent p2 p3) 
    (adjacent p3 p2) 
    (adjacent p3 p6)
    (adjacent p6 p9)
    (adjacent p6 p3)
    (adjacent p9 p8) 
    (adjacent p8 p9) 
    (adjacent p8 p7)
    (adjacent p7 p8) 
    (adjacent p7 p4)
    (adjacent p4 p7)  
    (adjacent p4 p1) 
    (adjacent p1 p4)
    (adjacent p2 p5) 
    (adjacent p5 p2) 
    (adjacent p5 p8)
    (adjacent p8 p5)  
  )
  (:goal
    (and
      (at  p1 n1) 
      (at  p2 n2) 
      (at  p3 n3)
      (at  p4 n4) 
      (at  p5 n5) 
      (at  p6 n6)
      (at  p7 n7) 
      (at  p9 n8) 
      (empty p8)
    )
  )
)